# GoReleaser config for Kaniko
# Version is read from .release-version into RELEASE_VERSION

version: 2

project_name: kaniko

builds:
  - id: executor
    binary: executor
    main: ./cmd/executor
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-mod=vendor
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-static"
      - -X 'github.com/Gosayram/kaniko/internal/version.Version={{ .Env.RELEASE_VERSION }}'
      - -X 'github.com/Gosayram/kaniko/internal/version.Commit={{ .Commit }}'
      - -X 'github.com/Gosayram/kaniko/internal/version.Date={{ .Date }}'
      - -s
      - -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm64
        goarm: "7"

  - id: warmer
    binary: warmer
    main: ./cmd/warmer
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-mod=vendor
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-static"
      - -X 'github.com/Gosayram/kaniko/internal/version.Version={{ .Env.RELEASE_VERSION }}'
      - -X 'github.com/Gosayram/kaniko/internal/version.Commit={{ .Commit }}'
      - -X 'github.com/Gosayram/kaniko/internal/version.Date={{ .Date }}'
      - -s
      - -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm64
        goarm: "7"

archives:
  - id: default
    # Includes built binaries + files below
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

signs:
  - id: checksum
    artifacts: checksum
    signature: "${artifact}.sig"
    cmd: gpg
    args:
      - "--batch"
      - "--pinentry-mode=loopback"
      - "--passphrase={{ .Env.GPG_PASSPHRASE }}"
      - "--default-key={{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

binary_signs:
  - id: binaries
    artifacts: binary
    signature: "${artifact}.sig"
    cmd: gpg
    args:
      - "--batch"
      - "--pinentry-mode=loopback"
      - "--passphrase={{ .Env.GPG_PASSPHRASE }}"
      - "--default-key={{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  mode: replace
  header: |
    ## Kaniko {{ .Tag }}

    Release {{ .Tag }} of Kaniko container image builder.

    ### Docker Images (signed with Cosign)

    Docker images are available at GitHub Container Registry (ghcr.io). All images are signed with Cosign:
    - `executor:{{ .Version }}` and `executor:latest`
    - `executor:{{ .Version }}-debug` and `executor:debug`
    - `executor:{{ .Version }}-slim` and `executor:slim`
    - `warmer:{{ .Version }}` and `warmer:latest`

    Verify image signatures using the public key from the repository:
    ```bash
    export USERNAME=<your-github-username>
    cosign login ghcr.io -u "$USERNAME"
    cosign verify --key cosign.pub ghcr.io/gosayram/kaniko/executor:{{ .Version }}
    ```

    The `cosign.pub` file is available in the repository root.

    ### Binaries (signed with GPG)

    This release includes the following binaries, signed with GPG:
    - `executor` - Main Kaniko executor
    - `warmer` - Kaniko cache warmer

    ### Installation

    Download the appropriate binary or archive for your platform from the assets below.

    ### Verification

    Verify checksums:
    ```bash
    sha256sum --check {{ .ProjectName }}_{{ .Version }}_checksums.txt
    ```

    Verify checksum signature:
    ```bash
    gpg --verify {{ .ProjectName }}_{{ .Version }}_checksums.txt.sig {{ .ProjectName }}_{{ .Version }}_checksums.txt
    ```

    Verify binary signatures:
    ```bash
    gpg --verify executor{{ .Version }}*.sig executor
    gpg --verify warmer{{ .Version }}*.sig warmer
    ```
  footer: |
    **Full Changelog**: https://github.com/Gosayram/kaniko/compare/{{ .PreviousTag }}...{{ .Tag }}{{ end }}


changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ with .AuthorUsername }} (@{{ . }}){{ end }}"
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "^chore: update$"
      - "^chore: docs$"
      - "^docs: update$"
      - "^chore: schema$"
      - "^chore: typo$"
      - "^chore: auto-update generated files$"
      - "^chore: update schema$"
      - "^chore: schema update$"
      - "^chore\\(deps\\): "
      - "^(build|ci): "
      - "merge conflict"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: '^.*?(\[ADD\]|\[ENHANCE\]|\[INIT\]|feat(\(.+\))?!?:|feature(\(.+\))?!?:|add(\(.+\))?!?:|init(\(.+\))?!?:|\[feature\/.+\]).*$'
      order: 100
    - title: "Performance improvements"
      regexp: '^.*?(\[perf\]|perf(\(.+\))?!?:).*$'
      order: 120
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))?!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(\[FIX\]|\[BUGFIX\]|fix(\(.+\))?!?:|bugfix(\(.+\))?!?:).*$'
      order: 200
    - title: "Refactoring"
      regexp: '^.*?(\[REFACTOR\]|refactor(\(.+\))?!?:).*$'
      order: 250
    - title: "Updates and Enhancements"
      regexp: '^.*?\[UPD\].*$'
      order: 300
    - title: "Documentation updates"
      regexp: '^.*?(\[DOCS\]|docs?(\(.+\))?!?:).*$'
      order: 400
    - title: "Tests"
      regexp: '^.*?(\[TEST\]|test(\(.+\))?!?:).*$'
      order: 450
    - title: "CI and Build"
      regexp: '^.*?(\[CI\]|\[CHORE\]|\[LINT\]|ci(\(.+\))?!?:|build(\(.+\))?!?:|chore(\(.+\))?!?:|lint(\(.+\))?!?:).*$'
      order: 500
    - title: "Dependencies"
      regexp: '^.*?Bump .*$'
      order: 600
    - title: "Other work"
      order: 9999